[package]
name = "locust"
version = "0.1.0"
edition = "2021"

[features]
debug_print_code = []
debug_trace_execution = []
default = ["debug_print_code", "debug_trace_execution"]

[dependencies]
num-traits = "0.2"
num-derive = "0.4"
gc = { version = "0.5", features = ["derive"] }
